# Generated by Django 5.2.13 on 2026-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
