# Generated by Django 5.2.13 on 2026-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
